CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burgers(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
burger_name VARCHAR(30) NOT NULL,
devoured BOOLEAN NOT NULL,
time_Stamp TIMESTAMP(6)
);

SELECT * FROM burgers;